baseURL: "https://blog.hossain.cc/" 
title: "Kazi"
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
# googleAnalytics: G-YB2G99Y2YS

minify:
    disableXML: true
    # minifyOutput: true




languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
        
        menu:
            main:
                - name: Links
                  url: links/
                  weight: 7

                - name: Bookshelf
                  url: bookshelf/

                - name: About
                  url: about/
                  weight: 5

                - name: Essays
                  url: essays/
                  weight: 4

                - name: Misc
                  url: miscellaneous/
                  weight: 6

                - name: Archive
                  url: archives
                  weight: 2

                - name: Search
                  url: search/
                  weight: 1

                - name: Topics
                  url: tags/
                  weight: 3
 

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Welcome to Kazi Hossain personal blog on topics such as Ai, Education, Books, Lifestyle, and More. Occasionally in this blog I also like to publish my notes from various classes or Technology I am learning. Think of this as my online thought garden. Don't miss out—stay updated with latest post by subscribing to the RSS feed."
    author: Kazi Hossain
    keywords: [Blog Kazi Hossain, Kazi Hossain Blog, Blog About Technology, Personal Blog Kazi Hossain, Kazi Hossain website]
    DateFormat: "January 2, 2006"
    disableThemeToggle: false


    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    disableScrollToTop: false
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: true
    ShowToc: true
    # comments: false
    images: ["kaziBanner.png"]
    hidemeta: false
    hideSummary: false

    profileMode:
        enabled: true
        title: Kazi Hossain
        imageUrl: "https://i.pinimg.com/564x/73/8f/f2/738ff21d48adbdf664fcbc26f4cde532.jpg"
        imageTitle: Kazi Hossain
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: all posts
              url: archives
            - name: Topics
              url: tags




            

    # homeInfoParams:
    #     Title: "PaperMod"
    #     Content: >
    #         Welcome to demo of hugo's theme PaperMod.

    #         - **PaperMod** is a simple but fast and responsive theme with useful feature-set that enhances UX.

    #         - Do give a 🌟 on Github !

    #         - PaperMod is based on theme [Paper](https://github.com/nanxiaobei/hugo-paper).

    socialIcons:
        - name: github
          url: "https://github.com/kazisean"
        - name: twitter
          url: https://twitter.com/KaziSean_
        - name: Rss
          url: "index.xml"

    # editPost:
    #     URL: "https://github.com/kazisean/blog/content"
    #     Text: "Suggest Changes" # edit text
    #     appendFilePath: true # to append file path to Edit link

    # label:
    #     text: "Home"
    #     icon: icon.png
    #     iconHeight: 35

    analytics:
        google:
             SiteVerificationTag: "h9unPlnjf006WcSUHEy_Ra2GawD6Ws8vyZs3KnDVeXM"

    # assets:
    # favicon: "https://raw.githubusercontent.com/kazisean/blogv2/main/static/favicon/favicon.ico"
    # favicon16x16: "https://raw.githubusercontent.com/kazisean/blogv2/main/static/favicon/favicon-16x16.png"
    # favicon32x32: "https://raw.githubusercontent.com/kazisean/blogv2/main/static/favicon/favicon-32x32.png"
    # apple_touch_icon: "https://raw.githubusercontent.com/kazisean/blogv2/main/static/favicon/apple-touch-icon.png"
    # # safari_pinned_tab: "/favicon/safari-pinned-tab.svg"

    cover:
         hidden: true # hide everywhere but not in structured data
         hiddenInList: true # hide on list pages and home
         hiddenInSingle: true # hide on single page


    fuseOpts:
            isCaseSensitive: false
            shouldSort: true
            location: 0
            distance: 1000
            threshold: 0.4
            minMatchCharLength: 0
            keys: ["title", "permalink", "summary", "content"]

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false
        # anchorLineNos: true
        # codeFences: true
        # guessSyntax: true
        # lineNos: true
        # style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true

sitemap:
changefreq: daily
priority: 0.8



            
outputs:
    home:
        - HTML
        - RSS
        - JSON
